### ISSUE TITLE
getting 404 page error

### ISSUE THREAD

**Issue by mywish1** [pxgamer/kickass-torrents-cp#6]
hi
when i click any of links i m getting error and can you tel me how to grab new torrents and this script works auto or i need to add torrents manually please explain all working model here how to get new torrents and getting result thanks please reply me as soon as possible

**Comment by PXgamer** [comment]
This is an abandoned project. KAT is dead. The code for this isn't finished yet.

Sorry, you'll need to add in the additional required functionality.

**Comment by PXgamer** [comment]
Also, please don't email me after 4 minutes of me not replying here. I'm on Github every day and will pick up any messages/issues here.
